cisco-open/camblet-driver

- README.md
> add presentation link

- device_driver.c
- device_driver.h
> Module entrypoint fixes

- .github/workflows/build.yml
- Makefile
> build the CLI and load an OPA module as a test in CI flow

- Makefile
Small NIT adding the -y flag to the makefile setup-vm command.
> Add -y flag to makefile setup-vm command

- .gitmodules
- README.md
> change default git URLs to https

- .github/workflows/build.yml
- Makefile
- README.md
- main.c
- opa.c
- proxywasm.c
- socket.c
A few memory corruption issues have been fixes, which somehow on ARM haven't caused any visible issues.
> Fix freezes on x86 (and possibly on ARM as well)

- Makefile
- opa.c
This example implements a opa_builtin1 function and to stands as an example for further implementations (and add a basic/cheap tracing capability to the opa part of the kernel module).
> add example for opa_builtin1 and small fixes

- Makefile
- csr.c
- csr.h
- device_driver.c
- main.c
- proxywasm.c
- proxywasm.h
- rsa_tools.c
- rsa_tools.h
- socket.c
This PR adds support for CSR generation using a wasm module written in rust. See: https://github.com/cisco-open/wasm-kernel-module/pull/29
> Generate CSR with wasm module

- .github/workflows/build.yml
> ci: add smoke test for proxy-wasm

- proxywasm.c
> fix x86 build

- socket.c
- test/file-server.go
> ipv6 support

- .github/workflows/build.yml
- Makefile
- README.md
- buffer.c
- buffer.h
- commands.h
- device_driver.c
- device_driver.h
- main.c
- proxywasm.c
- proxywasm.h
- socket.c
- socket.rego
fixes #58 
- proxywasm is disabled now by default
- proxywasm is not contacted if there are no proxywasm modules loaded
- improved buffer abstraction
- in the meantime the cli got rewritten, use that!
> proxy-wasm/TLS separation of concerns

- socket.c
- wasm-modules/csr-rust/src/main.rs
The first commit allows the addition of multiple subject alternate names to the csr. These values must be separated by a comma.
The second commit removes code duplication around the csr/cert generation in the socket.c
> Various enhancements and code compactation around cert generation

- Makefile
- README.md
- device_driver.h
- string.h
- task_context.c
The kernel module has changed directions since the original start/intent so we need to refactor the main README of the project.
> README refactoring

- .gitignore
- Makefile
Also removing other linux package dependencies.
> try to remove the rustup install on CI

- .github/settings.yml
- CODEOWNERS
> github: nasp-ify settings

- commands.c
- csr.c
- device_driver.c
- opa.c
- proxywasm.c
- socket.c
- tls.c
- wasm.c
Use the appropriate pr_ function instead of printk or FATAL.
> Use pr_* everywhere instead of printk and fatal

- opa.c
- opa.h
- tls.c
Refactor OPA policy evaluation.
> refactor opa policy eval

- .github/workflows/build.yml
- Makefile
- buffer.c
- commands.c
- commands.h
- csr.c
- csr.h
- device_driver.c
- device_driver.h
- opa.c
- opa.h
- proxywasm.c
- socket.c
- socket.h
- socket.rego
- task_context.c
- task_context.h
- tls.c
- tls.h
- wasm-modules/csr-rust/src/main.rs
- wasm.c
> Workload attestation

- .github/workflows/build.yml
- opa.c
- opa.h
- rsa_tools.c
- socket.c
- task_context.c
- task_context.h
- test/file-server.go
One or two steps towards #79 
Contains "Good old" BearSSL and kTLS fixes as well.
> TLS passthrough (manual)

- socket.c
These fixes provide some clean state now during closing connections and fixes some real CPU hog and messy log message issues.
Can be built and merged once the CLI WA branch is merged.
> Socket error and return value fixes

- .github/dependabot.yml
> setup dependabot for CI workflows for now

- .github/workflows/codeql.yml
> enable codeql

- attest.c
- cert_tools.c
- socket.c
We leak some memory currently, not just from the attest branch, but also the code already on the main branch, so trying to fix those.
After a few hours long of extensive connections going in and out, we can say there are no more leaks now.
> memory leak hunting

- Makefile
- attest.c
- attest.h
- cert_tools.c
- cert_tools.h
- commands.c
- commands.h
- device_driver.c
- socket.c
- task_context.c
- task_context.h
- third-party/parson/json.c
> Initial impl of attestation response caching

- Makefile
- config.c
- config.h
- device_driver.c
- main.c
- opa.c
adds trust domain configuration support
> add trust domain configuration support

- .github/workflows/build.yml
- commands.c
- commands.h
- opa.c
- opa.h
- socket.c
Add support to set specific cert TTL by policy rule.
> support setting cert ttl

- .github/workflows/build.yml
- Makefile
- cert_tools.c
- device_driver.c
- main.c
- sd.c
- sd.h
- socket.c
- socket.h
- string.c
- string.h
basic service discovery support
> basic service discovery

- Makefile
- README.md
- attest.c
- cert_tools.c
- commands.c
- csr.c
- device_driver.c
- main.c
- opa.c
- rsa_tools.c
- sd.c
- socket.c
- string.c
- tls.c
- wasm.c
change logging strategy to use pr_debug for most places and use dynamic debug if needed
> refactor logging

- Makefile
- README.md
- commands.h
- socket.h
> reduce build warnings during make

- Makefile
- csr.c
- debian/rules
- proxywasm.c
- sd.c
- socket.c
- wasm.c
I tried to run the module on a Pi Zero 2w running an aarch64 Raspberry Pi OS with 6.1.x kernel.
32bits is not supported yet.
> Raspberry pi (64bit) fixes 

- Makefile
- README.md
- main.c
- socket.c
- wasm.c
Use the kTLS feature only if it is available on the local system.
> add ktls_available parameter

- .github/workflows/build.yml
- Makefile
- attest.c
- attest.h
- augmentation.c
- augmentation.h
- commands.c
- commands.h
- socket.c
Align with the CLI changes around metadata gathering and change `workload attestation` to `process augmentation`.
> process metadata revamp

- opa.c
Updates rule structure change.
> update rule structure

- .github/workflows/build.yml
- augmentation.h
- commands.c
Adds support certificate chain with intermediates.
> support certificate chain with intermediates

- .github/workflows/release.yml
- .gitignore
- Makefile
- debian/source/options
- rpmbuild/SPECS/nasp-kernel-module.spec
Provide RPM package for the kernel module.
Related https://github.com/cisco-open/nasp/pull/76
> Create RPM packaging

- .github/workflows/build.yml
- Makefile
- scripts/update_versions.sh
Removes the global variables from the Makefile related to bump_version.
Fixes upgrade version script to upgrade main.c
> Upgrade bump_version target in Makefile

- opa.c
Related CLI PR https://github.com/cisco-open/nasp/pull/90
> harmonize policy api changes

- .github/workflows/build.yml
- .gitignore
- Makefile
Add setup-tls-perf target to makefile, with some documentation and add openssl client connect run to the smoketest.
> Add setup-tls-perf target and openssl to smoketest

- scripts/update_versions.sh
Now the update_versions.sh generates a change log to rpm spec files too.
> Add changelog to rpm spec as well

- .github/workflows/build.yml
Related CLI PR [cisco-open/camblet/pull/106]
> CLI enhancements

- trace.c
Every trace log message locks this mutex even if there are now trace requests, ease locking with this PR.
> trace: lock less if possible

- Makefile
> parametrize VERBOSE builds

- socket.c
> add sendfile support for non-ktls

- opa.c
- proxywasm.c
- wasm.c
- wasm.h
When there were no builtins required by the OPA module, we haven't linked any of the required OPA host functions. There were some error checking mistakes as well.
> opa: builtins parsing and some linkage fixes

- .github/workflows/build.yml
- .github/workflows/release.yml
Run actions only on the main branch and in case of a PR.
Tighten the release tag to x.x.x
> Run actions only on main and prs

- opa.c
- trace.c
fix trace log message size calculation
> fix trace log message size calculation

- Cargo.lock
- wasm-modules/csr-rust/Cargo.toml
- wasm-modules/csr-rust/src/main.rs
> rust: update crates and remove unused imports

- socket.c
Issues arise when testing it with camblet-driver and non camblet-driver connection.
> Revert "Handle TLS control messages in case of kTLS (#170) (#190)"

- test/smoke.sh
If some of the tests failed locally we had to do a manual cleanup.
> make test repeatable in case of an error

- src/socket.c
> Use is_ktls function instead of ktls_available

- src/socket.c
During ktls configuration we have to restore socket `proto_ops` as well (as for `proto` we do already). Otherwise our proto_ops poll will leak into other parts of the system where ktls is used (but we are not), and camblet module unload poisons those pointers.
> fix kTLS camblet stream ops leakage

- .github/workflows/build.yml
With this have more kernel version coverage:
-  5.15
- 6.5
- and now 6.8
> ci: run on ubuntu-24.04 as well

- .github/workflows/release.yml
Fix release yaml, remove the unnecessary with line from the make rpm.
> Fix with sentence in release.yaml
