cisco-open/camblet-driver

- Makefile
- device_driver.c
- hashtable.c
- netfilter.c
- opa.c
- opa.h
- proxywasm.c
- proxywasm.h
- runtime.c
- runtime.h
This is very draft version of this feature, that makes the kernel module accept and run [proxy-wasm](https://github.com/proxy-wasm/spec) modules:
After inserting the module to a Lima VM kernel, run:
```bash
cd wasm-kernel-module-cli
lima sudo ./cli/cli load -name proxywasm_tcp -file $HOME/Code/src/github.com/cisco-open/nasp/target/wasm32-unknown-unknown/release/wasm_tcp_metadata.wasm -entrypoint _start
lima sudo ./cli/cli load -name proxywasm_stats -file $HOME/Code/src/github.com/cisco-open/nasp/pkg/istio/filters/stats-filter.wasm -entrypoint _initialize
lima sudo sh -c "echo '{\"command\":\"proxywasm_test\"}' > /dev/wasm"
```
> basic proxy-wasm module support

- socket.c
- socket.h
The socket type method is removed in favour of the new "transparent" socket type.
> remove socket type and inet_ methods

- README.md
- device_driver.c
- device_driver.h
- proxywasm.c
- socket.c
Command sending is implemented now in a synchronous fashion with the external user-space agent. There is a 5 second timeout of waiting for command answers.
See https://github.com/cisco-open/wasm-kernel-module-cli/pull/11
Usage:
```bash
cd wasm-kernel-module-cli
make build-cli
lima sudo ./w3k server
```
> implement sync command answering

- Makefile
- csr.c
- csr.h
- device_driver.c
- main.c
- proxywasm.c
- proxywasm.h
- rsa_tools.c
- rsa_tools.h
- runtime.c
- socket.c
This PR generates a rsa keypair inside a kernel using bearSSL. The stored key will then be used to generate a certificate signing request using a wasm module. (bearSSL at the moment does not support this). This CSR will then be used in an agent code(e.g.: istio controlplane) to generate a proper certificate.
The used module can be found: https://github.com/cisco-open/wasm-kernel-module-cli/tree/main/samples/csr-rust
> Generate CSR using wasm module

- device_driver.c
- runtime.c
- socket.c
Things have changed in kernel 6.4, see:
- https://elixir.bootlin.com/linux/v6.4/source/include/linux/uio.h#L72
- https://elixir.bootlin.com/linux/v6.4/source/include/linux/device/class.h#L230
Also fixing an under allocation for the module name string, which only bubbled up in this kernel version.
> fix iov_length query and device class_create on 6.4 kernel

- proxywasm.c
- socket.c
This caused nasty issues during socket close.
Also updating the tcp metadata filter from nasp to the current version.
> socket: add missing proxywasm locking and context setting

- device_driver.c
- socket.c
It causes freezes on x86 and it isn't a good idea in general.
> don't use stack values in command wait

- .gitignore
- Makefile
- device_driver.c
- main.c
- opa.c
- proxywasm.c
- proxywasm.h
- rsa_tools.c
- socket.c
- socket.rego
This PR adds the capability to evaluate connections based on [Rego](https://www.openpolicyagent.org/docs/latest/policy-language/) policies, if they should be intercepted by the Wasm based protocol filter engine.
```rego
package socket
allowed_ports := {8000, 8080}
allowed_commands := {"curl", "python3"}
allow {
allowed_ports[input.port]
allowed_commands[input.command]
}
```
> proxywasm: opa based connection eval

- opa.c
- opa.h
- socket.c
- socket.rego
- third-party/parson/json.c
OPA socket evaluation policies can return a complex object from now on and it is parsed by the socket.c evaluations in accept/connect, thus enabling us to turn mTLS on/off through it.
> opa: make mTLS optional via opa contexts

- proxywasm.c
- proxywasm.h
- socket.c
This PR adds the ability to the wasm filters to work with Action::Continue and Action::Pause.
It also reallocates the write and read buffers if it is not big enough.
Fixes #26
> Implement Continue and Pause for wasm filters

- .github/workflows/build.yml
- Makefile
- README.md
- dkms.conf
- socket.c
- socket.rego
Currently only the TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 cipher is implemented, this is the default cipher of BearSSL.
Fixes https://github.com/cisco-open/wasm-kernel-module/issues/54
Contains a lot of (untracked) other fixes and a small test that verifies that sendfile works with kTLS (via NGiNX).
- add test for app without kTLS (I have added a test, but it works locally only, somehow not on GH Actions)
- add test with nginx (sendfile should be stressed)
> kTLS support

- csr.c
- csr.h
- socket.c
This PR allows to add Certificate Signing Request parameters. Now the values are hardcoded but can be replaced easily.
Fixes #53
> Allow to add csr parameters

- Makefile
- commands.c
- commands.h
- device_driver.c
- device_driver.h
- socket.c
- task_context.c
- task_context.h
> add common context to commands

- Makefile
- commands.c
- commands.h
- csr.c
- device_driver.c
- rsa_tools.c
- rsa_tools.h
- socket.c
- string.c
- string.h
> retrieve signed x509 cert from agent

- Makefile
- commands.c
- device_driver.c
The sleep loop for waiting for commands to be processed was inefficient since it locks and unlocks the lock in every loop iteration. Besides that the worst case delay could be almost the double of the inner sleep time, which now becomes zero.
> driver: use exact signaling instead of sleep loop

- commands.c
- device_driver.c
- proxywasm.c
- socket.c
- string.c
- wasm.c
When running on centos-stream-9 the module had certain memory allocation issues, which turned out to be global issues, they are just not present on later kernel and gcc versions.
> memory-allocation fixes

- .github/workflows/build.yml
This speeds up the build with reducing network traffic by caching go pkgs.
> ci: setup go with caching for cli build

- .github/workflows/build.yml
- Makefile
This reduces build time also, but the main point of this is to test our official installation method (and only that) during the builds, which is DKMS. Install less garbage during GitHub Actions runs.
> ci: excercise (only) DKMS during the builds

- Makefile
- cert_tools.c
- cert_tools.h
- commands.c
- commands.h
- device_driver.c
- device_driver.h
- opa.h
- rsa_tools.c
- rsa_tools.h
- socket.c
Implement cert bundle caching.
From now on, if the certificate used by the server/client is valid, it will be reused.
This is the initial implementation of caching, which uses a linked list and removes the certificate bundles only if they are no longer valid. During the next iteration, we are going to introduce some form of garbage collection to this cache.
> Initial impl of cert bundle caching

- attest.c
- commands.c
- socket.c
The refcount should be incremented while holding the lock on the cache, otherwise housekeeping could pull the rug out from under us in a racy moment.
> Attest cache fixes

- cert_tools.c
Since we are calling list_add in the next step initializing the list pointers are not required.
> Remove Init list head in case of cert cache

- socket.c
We weren't passing the precious `flags` parameter down to the deepest `recv` function, so now I'm fixing that!
Also give support for `MSG_PEEK` (`wget` for example uses it) in BearSSL since it doesn't support any kind of flags by default. `sendfile` (used by `nginx`, but can be turned off in configuration) still doesn't work with pure BearSSL before kernel versions 6.5, see https://github.com/cisco-open/nasp-kernel-module/issues/56
> support flags parameter in nasp_recv_msg function

- Makefile
- wasm.c
On older distros true/false are not valid kernel module parameters.
> fix insmod around tls

- .vscode/c_cpp_properties.json.template
- debian/prerm
- dkms.conf
- main.c
- The module description was heavily outdated.
- The module dependency on `tls` was only incidental.  Now it is determenestic (via `MODULE_SOFTDEP`):
```sh
$ sudo modprobe -v nasp
insmod /lib/modules/6.2.0-39-generic/updates/dkms/bearssl.ko 
insmod /lib/modules/6.2.0-39-generic/kernel/net/tls/tls.ko 
insmod /lib/modules/6.2.0-39-generic/updates/dkms/nasp.ko 
```
- Remove the module on uninstallation.
- Actualize VSCode CPP config.
> fix module description, loading and stuff

- device_driver.c
- main.c
- opa.c
- wasm.c
Online CPUs reflect much better how many CPUs are available currently on a given system, possible CPUs caused creation of more CPUs than really available on cloud environments.
Also don't use the nr_cpu_ids variable directly, instead call num_online_cpus()
> using online CPU count instead of possible

- nasp.h
- socket.c
- tls.c
- tls.h
This PR introduces a new socket option to enable the NASP ULP on the socket programatically, thus no agent is needed (this can be done from kernel and user space code as well):
NOTE: currently server CA verification is not yet implemented, so we run with 'insecure skip verify' mode.
```c
error = sock_create(AF_INET, SOCK_STREAM, IPPROTO_TCP, &sock);
if (error < 0)
{
printk(KERN_ERR "error creating socket\n");
return error;
}
// Enable the nasp middleware for this socket
sock->ops->setsockopt(sock, SOL_TCP, TCP_ULP, KERNEL_SOCKPTR("nasp"), sizeof("nasp"));
// Set hostname for validation
char hostname[] = "aws.amazon.com";
sock->ops->setsockopt(sock, SOL_NASP, NASP_HOSTNAME, KERNEL_SOCKPTR(hostname), sizeof(hostname));
```
https://github.com/bonifaido/test-kernel-module/blob/main/main.c#L46
> setsockopt controllable client TLS enablement

- socket.c
Otherwise each nasp socket initialization (and ktls prot overwrite) could overwrite each other.
> fix kTLS vs nasp TCP proto override

- debian/prerm
- tls.c
Make the SPIFFE ID check trust domain prefixable, i.e:
Required Spiffe ID `spiffe://alma/korte` should match `spiffe://alma/korte/kisbeka` as well, but not `spiffe://alma/kortekisbeka`
> SPIFFE ID check refactor

- Makefile
- commands.c
- commands.h
- device_driver.c
- opa.c
- opa.h
- socket.c
- socket.h
- task_context.c
- tls.c
- tls.h
- trace.c
- trace.h
Related driver PR [cisco-open/camblet#108]
This PR implements connection event tracing capability.
There is a new entity called `trace request`. The CLI agent is able to register request for UID, PID, command name or a combination for them for tracing events realtime.
The driver send one-way trace messages to the CLI agent based on those requests.
> connection event tracing

- commands.c
- socket.c
- socket.h
- tls.c
- tls.h
fixes: #79 
If TLS is detected by the client, it tries to negotiate it with the server side (through ALPN) of Camblet and if they agree, Camblet is not doing double record encryption.
> socket: implement automatic TLS passthrough

- camblet.h
- socket.c
- socket.h
- tls.c
- tls.h
Introduce new socket option (CAMBLET_TLS_INFO) to get local and peer SPIFFE IDs for a connection.
> support getting connection spiffe ids through socket option

- device_driver.c
- opa.c
- proxywasm.c
Report underlying dynamic error in case of wasm module compiling loading at all places. Currently we report only the constant error identifier (in C this is the way).
> proper and verbose wasm module error printing

- .github/workflows/build.yml
- socket.c
kTLS is now able to handle TLS control messages relying on bearSSL.
Fixes #60
> Handle TLS control messages in case of kTLS

- socket.c
This reverts commit d9e8420b030f7fe96cec6b509a856e13ea0b85a6.
Currently this is broken on 5.15 x86
See various runs of: https://github.com/cisco-open/camblet-driver/pull/182
> Revert "Handle TLS control messages in case of kTLS (#170)"

- .github/workflows/build.yml
- socket.c
Introduce a basic matrix build, so we test on ubuntu 22.04 (kernel 6.5) and on 20.04 (kernel 5.15) as well.
> ci: use build matrix to test on 6.5 and 5.15 kernel as well

- .github/actions/smoketest/action.yaml
- .github/workflows/build.yml
- socket.c
- test/smoke.sh
This PR fixes `-ERESTARTSYS` retval  during TLS handshake and propagates `-EINTR` up to userspace if the socket is not shutdown, previously it was not handled at all, which caused interrupted handshakes in some cases.
> handle -ERESTARTSYS during TLS handshake

- socket.c
Use the camblet_sendpage in case of kTLS otherwise, various errors arise when a server tries to use sendpage.
> Use camblet_sendpage in case of kTLS under kernel version 6.5

- socket.c
Handle TLS control messages in case of kTLS
> Handle TLS control messages in case of kTLS (#170)

- socket.c
- test/smoke.sh
- tls.c
- tls.h
Add support for aes GCM and CCM based ciphers when using kTLS.
> Support aes gcm and ccm ciphers

- Makefile
- sd.c
- socket.c
Close ordering fix in case of BearSSL connections to avoid memory corruption.
Lock BearSSL state properly, to make it work we need to employ non-blocking reads and proper return values are necessary.
Related BearSSL PR: https://github.com/bonifaido/BearSSL/pull/7/files
> socket: fix bearssl close order

- socket.c
We forced a busy loop for non-blocking applications (CPU 100%) instead of propagating the error code that they are prepared to handle, since they requested `MSG_DONTWAIT`. This PR fixes this.
> socket: propagate non-block error codes upwards

- test/smoke.sh
Re-add test which tests fileserver using curl, since the bearSSL closing issue was fixed.
> Re-add test fileserver using curl

- socket.c
- test/smoke.sh
Fixes: #179 
BearSSL reads full TLS records, but the upper application doesn't know that, and if it waits for new data to be read for example with a select(), it will never get notified since the data is already in the BearSSL buffer. This fix overcomes this situation.
> socket: fix for bearrssl pre-read data vs poll()

- socket.c
This pull request introduces read and write buffer locks to the camblet_sendmsg and camblet_recvmsg functions. Additionally, it addresses discrepancies in kernel versions about the MSG_DONTWAIT flag for kTLS.
> Add read/write buffer lock during send/recvmsg

- .github/workflows/build.yml
- include/camblet.h
- src/commands.c
- src/socket.c
- test/file-server.go
- test/smoke.sh
- test/sockopt.c
Original getsockopt restoration in module exit was missing (interesting situations could occur after module unload...), but from now on it is not needed since the overwrite is socket local.
Fixing tcp_connection_context memory placing issue in camblet_setsockopt.
Fix for CPU hog read waits.
Added test for Camblet sockopt functions.
Check the commits for all the fixes.
> socket: fixes around camblet_get/setsockopt and recvmsg waiting and other things

- src/socket.c
The title is self-explanatory.
> socket: fix leaking tcp_connection_contexts and opa objects

- .github/workflows/release.yml
This PR adds an install step to the release phase. It helps to fail fast in case of a package error.
> Add Debian package test to release process

- src/device_driver.c
- src/trace.c
This PR fixes the following trace request issues:
- 'command_name' should not be required
- fix double free of task context
> [bugfix] trace request

- Makefile
- include/wasm.h
- src/augmentation.c
- src/commands.c
- src/config.c
- src/device_driver.c
- src/proxywasm.c
- src/sd.c
- src/socket.c
- src/task_context.c
- src/wasm.c
[some fixes on fedora (and kernel 6.8)](https://github.com/cisco-open/camblet-driver/pull/219/commits/1b924934af7156d8750f0605011aab04c5160a89)
[fix rcu locking](https://github.com/cisco-open/camblet-driver/pull/219/commits/869038a7be9df11aad28ca97c4665a1515228ab2)
[sd: fix broken removing iteration](https://github.com/cisco-open/camblet-driver/pull/219/commits/17eba7bd947810fa498b7a9e009ac5ea5833da10)
[pre-compile modules after loading](https://github.com/cisco-open/camblet-driver/pull/219/commits/062299139cbbcc486ce6accb6cb97a6c3dca63e0)
[proxywasm leak fixes](https://github.com/cisco-open/camblet-driver/pull/219/commits/581ee6e53566f8a6a68da336d7b464b28d7fa961)
[point to rebased wasm3](https://github.com/cisco-open/camblet-driver/pull/219/commits/4b29103dd75cc6fe17468a849a13148d7c5b8118 …
> memory corruption and RCU fixes (for bugs discovered on a debug kernel)

- include/trace.h
- src/trace.c
> refactor trace log to macros

- Makefile
- README.md
- include/augmentation.h
- include/cert_tools.h
- include/csr.h
- include/opa.h
- src/augmentation.c
- src/cert_tools.c
- src/csr.c
- src/main.c
- src/opa.c
- src/socket.c
- third-party/picohttpparser/picohttpparser.c
[disable KASAN for m3_compile (stackoverflow issue)](https://github.com/cisco-open/camblet-driver/commit/d5cdd6dd89e7d4c159dc36adc1af06b7e6f165ea)
[update wasm3 to avoid module name leaks](https://github.com/cisco-open/camblet-driver/commit/eb762d38745816ab5a1cfb6a93059f9747e6b205)
[cert cache and wasm module leak fix](https://github.com/cisco-open/camblet-driver/commit/99d4a06784da1c2cf0757ffb84caa1dc7670e0b0)
[fix augmentation cache leak on exit](https://github.com/cisco-open/camblet-driver/pull/223/commits/8093d658d8ab580fc811e20cfd195e4aa8ffa61a)
[picohttpparser: remove x86 intrinsics in kernel](https://github.com/cisco-open/camblet-driver/pull/223/commits/f924a3fd6553627cda5effb5d3bb1018221469d7)
> another round of memory leak fixes (the last one)

- include/proxywasm.h
- src/device_driver.c
- src/main.c
- src/proxywasm.c
- src/socket.c
- src/wasm.c
- free proxywasm instances on exit
- log compile errors, but don't fully compile proxywasm modules (pre-compile)
- also implementing get nanoseconds in proxywasm
> fix proxywasm leaks

- Makefile
- debian/source/options
Exclude bats and wasm3/platform dirs from debian and redhat builds.
> Exclude bats and wasm3/platform dirs from debian and rpm build

- src/device_driver.c
Red Hat based Linux distros use an esoteric signature for this function compared to mainline kernel.
> fix class_create compile error on red hat linux

- .github/workflows/release.yml
Generate attestation for both artefacts in a single step.
> Fix attestation job by providing both artefacts

- .github/workflows/release.yml
Do not use a relative path inside the attestation job.
> Do not use relative path inside attention job
